version: '3'
services:
  web:
    build:
      context: .
      target: http-server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  socket:
    build:
      context: .
      target: socket-server
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"